### ISSUE TITLE
L2 Distortion Loss

### ISSUE THREAD

**Issue by FantasticOven2** [hbb1/diff-surfel-rasterization#13]
Hey Author,

Thanks for this great work! I wonder why do you choose a L2 depth distortion loss instead of L1 loss proposed here [https://arxiv.org/pdf/2206.05085](url)

**Comment by hbb1** [comment]
Hi,  because the intersection depth $z$ may not be sorted in Gaussian Splatting, so that it is non trival to adopt $L1$ depth distortion loss, because we cannot factorize the term outside the L1 norm.

**Comment by hbb1** [comment]
On the other hand, using the L2 loss we have


$$L= \sum_{i=0}^{N-1}\sum_{j=0}^{N-1}w_iw_j(d_i-d_j)^2 = \sum_{i=0}^{N-1}\sum_{j=0}^{N-1}w_iw_j(d_i^2-2d_id_j+d_j^2)$$

This will allows us to reformulate a nested algorithm to be implemented in a single pass.
