### ISSUE TITLE
[2dgs paper] Equation 7 - 10

### ISSUE THREAD

**Issue by zixunh** [hbb1/diff-surfel-rasterization#23]
Maybe several silly questions, let me know if I missed any details.
- Why you express the screen space points as (xz, yz, z, 1), is this exactly what you derived in your code with the world2ndc and ndc2world matrix?
- the math definition in equation 7 seems inconsistent with equation 8-10, given a pixel (x,y), if you want to express the ray-splat intersection through 3 planes, shouldn't the 4d homogenous planes also include the depth z of the intersection? Or do you keep the ndc coordinates for the rays in the intersection operations?

**Comment by hbb1** [comment]
- Hi, splat2world is **H** and (world2ndc * ndc2pix) is **W** in the paper. It may be somewhat confusing that why there is a ndc transform, this is because that we use the 3DGS camera format so we need further to convert the ndc projection matrix back to screen space. We express a 3d screen space point as (xz, yz, z)  so that we can express its 2d projection as (x,y). 
- Since we have already used homogeneous coordinate representation, there is no need to explicitly include the depth z.  Here is a more intuitive explanation for Eq. 8~Eq.10: the cross product of two plane is a line. A line (i.e, 3d homogenous point) can be transformed back to a 2d point through perspective division.

**Comment by zixunh** [comment]
ic. When you mentioned screen space here and in the paper, you're actually want to say the view space or the clip space, right?

But I thought that you only used ndc space and the object space in your equation 8-10.

**Comment by zixunh** [comment]
to make my question simpler, in the code, W is made by world2ndc and ndc2pixel.

WH(u,v,1,1)^T should derive to the point in the pixel space or screen space. I can understand if it's x,y,1; or it's a homogeneous vector xw, yw, w. 

May you explain more why it can also be xz,yz,z,1 where z is the depth

**Comment by hbb1** [comment]
Hi, isn't it how we project a 3D point into a 2D screen?

(xz,yz,z,1) = (K [R | t]) H (u,v,1,1)^T

**Comment by zixunh** [comment]
for the K, you mean the projective matrix often used in graphics, rather than the 3by3 intrinsic often in CV, right?

**Comment by hbb1** [comment]
**K** shoud be a 3x3 intrinsic matrix and here I assume it is padded to 4x4. [R | T] also denote 4x4 world2cam matrix.
(Sorry I am a CV guy and I don't exactly  know what projective matrix as there are two many projection matrix ...)

If you want to check further details to understand the transform, [here](https://colab.research.google.com/drive/1qoclD7HJ3-o0O1R8cvV3PxLhoDCMsH8W?usp=sharing) is a python demo for you.

**Comment by zixunh** [comment]
Emm, but in the codes, I saw the full projective matrix was calculated through FoVx FoVy and also the far plane and near plane. Which is typical graphics transformation. And then you feed it into the rasterazation cuda codes. I will check that again.

**Comment by hbb1** [comment]
> * Hi, splat2world is **H** and (world2ndc * ndc2pix) is **W** in the paper. It may be somewhat confusing that why there is a ndc transform, this is because that we use the 3DGS camera format so we need further to convert the ndc projection matrix back to screen space. We express a 3d screen space point as (xz, yz, z)  so that we can express its 2d projection as (x,y).
> * Since we have already used homogeneous coordinate representation, there is no need to explicitly include the depth z.  Here is a more intuitive explanation for Eq. 8~Eq.10: the cross product of two plane is a line. A line (i.e, 3d homogenous point) can be transformed back to a 2d point through perspective division.

Exactly. As I mentioned before, our code takes 3DGS camera format (which use projection) and we made conversion througth (world2ndc * ndc2pix)
