### ISSUE TITLE
Orthophoto rendering

### ISSUE THREAD

**Issue by Golbstein** [hbb1/diff-surfel-rasterization#25]
Hello
In the original 3dgs to be able to render orthophoto I had to change slightly the forward.cu function as described here:

https://github.com/graphdeco-inria/gaussian-splatting/issues/578#issuecomment-2365040949

what's the analogous modification in your rasterizer?

**Comment by Golbstein** [comment]
I only had to change the projection matrix and it worked

**Comment by shine157** [comment]
Hello, could you share the code
