### ISSUE TITLE
On the Filter Size 

### ISSUE THREAD

**Issue by hbb1** [hbb1/diff-surfel-rasterization#4]
If a filter is small enough, we are able to approximate a pixel using a point, so as to achieving high accuracy. However, if the filter is too small,  gradient can not be well received. So Here is a trade-off.

**Comment by hbb1** [comment]
@JIANG-CX  Sorry, I cannot find my original code, but I think it should be easy for you to use gsplat framework (already integrating 2DGS) for conducting such experiments (using the image fitting script and initializing the points with small scales).

**Comment by JIANG-CX** [comment]
ok, thanks for your reply.


获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Binbin ***@***.***>
发送时间: Wednesday, August 28, 2024 5:48:33 PM
收件人: hbb1/diff-surfel-rasterization ***@***.***>
抄送: JIANG Chenxing ***@***.***>; Mention ***@***.***>
主题: Re: [hbb1/diff-surfel-rasterization] On the Filter Size (Issue #4)


@JIANG-CX<https://github.com/JIANG-CX> Sorry, I cannot find my original code, but I think it should be easy for you to use gsplat framework (already integrating 2DGS) for conducting such experiments (using the image fitting script and initializing the points with small scales).

―
