### ISSUE TITLE
Please explain compute_aabb

### ISSUE THREAD

**Issue by AlexRoss-WHS** [hbb1/diff-surfel-rasterization#8]
Hi, thank you for providing the code and for your great paper!
Could you please explain the compute_aabb function to me? https://github.com/hbb1/diff-surfel-rasterization/blob/a97d67aed599ab99dad4ecbe1dc5751bf4f16562/cuda_rasterizer/forward.cu#L122-L148
I can't quite understand how it is derived.

**Comment by CanCanZeng** [comment]
I can't understand this part either. If you understand, please let me know. Thank you @AlexRoss-WHS

**Comment by hbb1** [comment]
![image](https://github.com/hbb1/diff-surfel-rasterization/assets/57170935/c3707a85-7322-4043-b9ad-9131a36d61aa)

**Comment by CanCanZeng** [comment]
Thank you for answering my question perfectly @hbb1

**Comment by AlexRoss-WHS** [comment]
Thank you @hbb1 for taking the time for such a detailed answer! Now that I understand the code and maths I think there are two small typos in your answer:

1. It sould be $b = -2 * \text{sum}(f T_0 T_3)$
2. and ${x_1 + x_2 \over 2} ={ -b \over 2 a}$

**Comment by hbb1** [comment]
Hi, everyone. @CanCanZeng @AlexRoss-WHS @FantasticOven2 
In case you are not aware of it, there is a bug in the current AABB computation. We should directly calculate 3 sigma AABB in the object space instead of calculating 1 sigma AABB and multiplying it with 3 in the screen space. The reason is here #15

**Comment by xingcheng1061** [comment]
> ![image](https://private-user-images.githubusercontent.com/57170935/334928516-c3707a85-7322-4043-b9ad-9131a36d61aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwMzIyNjksIm5iZiI6MTcyNjAzMTk2OSwicGF0aCI6Ii81NzE3MDkzNS8zMzQ5Mjg1MTYtYzM3MDdhODUtNzMyMi00MDQzLWI5YWQtOTEzMWEzNmQ2MWFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDA1MTkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2ZGU1NjI4MDY3MWIxMmUyNzkyZWYyYmI5ZGQ5YTJmMmI1Zjg2MjBjOTlhNDgzOWFhMzJiZWUxOGQzOGMyZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0exPzoQOEpWFRG-wAwBLnjH3Sfvu13g6c5b5UTkHnq0)

作者您好，这个里面的公式似乎存在一点问题，(x1+x2)/2=-b/2a，而不是-b/a，不知道代码中是否也存在这个错误？

**Comment by xingcheng1061** [comment]
> ![image](https://private-user-images.githubusercontent.com/57170935/334928516-c3707a85-7322-4043-b9ad-9131a36d61aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwMzIyNjksIm5iZiI6MTcyNjAzMTk2OSwicGF0aCI6Ii81NzE3MDkzNS8zMzQ5Mjg1MTYtYzM3MDdhODUtNzMyMi00MDQzLWI5YWQtOTEzMWEzNmQ2MWFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDA1MTkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2ZGU1NjI4MDY3MWIxMmUyNzkyZWYyYmI5ZGQ5YTJmMmI1Zjg2MjBjOTlhNDgzOWFhMzJiZWUxOGQzOGMyZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0exPzoQOEpWFRG-wAwBLnjH3Sfvu13g6c5b5UTkHnq0)

作者您好，论文中提到公式X=(xz,yz,z,z)^T = WP(u,v) = WH(u,v,1,1)^T，按照二维高斯的uv坐标系定义，高斯中心的uv坐标应为(0,0)，为何不直接将u=0，v=0代入该公式中解出x和y呢？
